name: csv_sheets_uploader
description: Utility to upload CSV or TSV files to Google Sheets
version: 0.0.1
author: Ray Rischpater, KF6GPE <rischpater@google.com>

environment: 
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.5.0
  csv:  ^4.0.0